name: BGM_replication
channels:
- conda-forge
dependencies:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - slycot
    - xlwt
    - pip
    - pip:
        - git+https://github.com/EconForge/dolo.git
